#port
server:
  port: 8761

#eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-client: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
