spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:file:~/products;AUTO_SERVER=true
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

#eureka
eureka:
  instance:
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#axon
axon:
  eventhandling:
    processors:
      product-group:
        mode: tracking

# log level
logging:
  level:
    org:
      axonframework:
        axonserver:
          connector:
            event:
              axon:
                AxonServerEventStore: DEBUG
