spring:
  application:
    name: user-service

server:
  port: 0

eureka:
  instance:
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
